# Document type definitions for validation
document_types:
  service_report:
    name: "Service Report"
    description: "Standard technical service call report"
    required_fields:
      - date_of_service
      - technician_name
      - customer_poc
      - problem_description
      - work_performed
      - issue_resolved
      - next_steps
    
  pm_report:
    name: "Preventative Maintenance Report"
    description: "Regular scheduled maintenance report"
    required_fields:
      - date_of_service
      - technician_name  
      - customer_poc
      - work_description  # Accept either "description of service" OR "description of work performed"
      - completion_status # Accept either "service completed" OR "issue resolved"
      - next_steps