# Field definitions for document validation
fields:
  date_of_service:
    display: "Date of service"
    canonical: "**Date of service:**"
    semantic_alternatives:
      - "Service date"
      - "Date"
      - "Date of visit"
    
  technician_name:
    display: "Technician name"
    canonical: "**Technician name:**"
    semantic_alternatives:
      - "Technician"
      - "Tech name"
      - "Service technician"
  
  customer_poc:
    display: "Customer point of contact"
    canonical: "**Customer point of contact:**"
    semantic_alternatives:
      - "Client contact"
      - "Contact person"
      - "Point of contact"
      - "Customer contact"
    allow_plural: true
  
  problem_description:
    display: "Description of problem"
    canonical: "**Description of problem:**"
    semantic_alternatives:
      - "Problems and requests"
      - "Issues reported"
      - "Problems encountered"
      - "Service request"
      - "Reported issue"
    allow_plural: true
    allow_capital: true

  work_performed:
    display: "Description of work performed"
    canonical: "**Description of work performed:**"
    semantic_alternatives:
      - "Work performed"
      - "Service performed"
      - "Actions taken"
      - "Work completed"
  
  issue_resolved:
    display: "Issue resolved"
    canonical: "**Issue resolved?**"
    semantic_alternatives:
      - "Problem resolved"
      - "Resolution status"
      - "Resolved"
    allow_plural: true
    question_mark: true
  
  next_steps:
    display: "Next steps"
    canonical: "**Next steps?**"
    semantic_alternatives:
      - "Future actions"
      - "Follow-up required"
      - "Follow-up actions"
      - "Recommended next steps"
    question_mark: true